version: "3.3"
services:
  urbit-umbrel:
    image: mopfelwinrux/urbit-umbrel:latest
    ports:
      - "34343:34343"
      - "8090:8090"
    volumes:
      - .app/piers:/data/piers
      - .app/keys:/data/keys
    environment:
      FLASK_ENV: development
      FLASK_APP: app
