version: "3.3"
services:
  urbit-umbrel:
    build: .
    ports:
      - "5000:5000"
      - "34343:34343"
      - "50080:80"
      - "8090:8090"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
